/**
 * Legal & Trademark Configuration
 * Centralized settings and helper functions for branding and legal text.
 */

export interface LegalConfig {
  brandName: string;
  trademarkStatus: "TM" | "R";
  showPatentPending: boolean;
  legalOwner: string;
  brandWithMark: () => string;
  legalYear: () => number;
  legalLine: () => string;
  exportWatermark: (orgName?: string) => string;
}

const baseConfig: Omit<LegalConfig, "brandWithMark" | "legalYear" | "legalLine" | "exportWatermark"> = {
  brandName: "Clockwork Venue",
  trademarkStatus: "TM", // "TM" for trademark, "R" for registered trademark
  showPatentPending: false,
  legalOwner: "Digital Visionworks LLC",
};

const legalYear = (): number => new Date().getFullYear();

const brandWithMark = (): string => {
  const symbol = baseConfig.trademarkStatus === "R" ? "\u00AE" : "\u2122";
  return `${baseConfig.brandName}${symbol}`;
};

const legalLine = (): string => {
  let line = `\u00A9 ${legalYear()} ${baseConfig.legalOwner}. All rights reserved. ${brandWithMark()} and the ${baseConfig.brandName} logo are trademarks of ${baseConfig.legalOwner}.`;
  if (baseConfig.showPatentPending) {
    line += " Patent pending.";
  }
  return line;
};

const exportWatermark = (orgName: string = "Default Org"): string => {
  const timestamp = new Date().toISOString();
  return `Generated by ${brandWithMark()} \u2014 stageflowlive.com \u2014 Org: ${orgName} \u2014 ${timestamp}`;
};

export const legalConfig: LegalConfig = {
  ...baseConfig,
  brandWithMark,
  legalYear,
  legalLine,
  exportWatermark,
};
